export default [{
  "id": 1,
  "first_name": "Iggy",
  "dollars_spent": 243
}, {
  "id": 2,
  "first_name": "Robbin",
  "dollars_spent": 315
}, {
  "id": 3,
  "first_name": "Maggy",
  "dollars_spent": 45
}, {
  "id": 4,
  "first_name": "Todd",
  "dollars_spent": 179
}, {
  "id": 5,
  "first_name": "Riki",
  "dollars_spent": 134
}, {
  "id": 6,
  "first_name": "Ronnie",
  "dollars_spent": 461
}, {
  "id": 7,
  "first_name": "Cicely",
  "dollars_spent": 440
}, {
  "id": 8,
  "first_name": "Adams",
  "dollars_spent": 373
}, {
  "id": 9,
  "first_name": "Jana",
  "dollars_spent": 239
}, {
  "id": 10,
  "first_name": "Paulina",
  "dollars_spent": 179
}, {
  "id": 11,
  "first_name": "Frank",
  "dollars_spent": 109
}, {
  "id": 12,
  "first_name": "Dal",
  "dollars_spent": 412
}, {
  "id": 13,
  "first_name": "Gilberta",
  "dollars_spent": 435
}, {
  "id": 14,
  "first_name": "Maddie",
  "dollars_spent": 198
}, {
  "id": 15,
  "first_name": "Barbee",
  "dollars_spent": 33
}, {
  "id": 16,
  "first_name": "Hilton",
  "dollars_spent": 241
}, {
  "id": 17,
  "first_name": "Robena",
  "dollars_spent": 212
}, {
  "id": 18,
  "first_name": "Vinita",
  "dollars_spent": 124
}, {
  "id": 19,
  "first_name": "Lora",
  "dollars_spent": 101
}, {
  "id": 20,
  "first_name": "Reina",
  "dollars_spent": 81
}, {
  "id": 21,
  "first_name": "Xylia",
  "dollars_spent": 179
}, {
  "id": 22,
  "first_name": "Bing",
  "dollars_spent": 205
}, {
  "id": 23,
  "first_name": "Veradis",
  "dollars_spent": 491
}, {
  "id": 24,
  "first_name": "Cris",
  "dollars_spent": 334
}, {
  "id": 25,
  "first_name": "Fianna",
  "dollars_spent": 171
}, {
  "id": 26,
  "first_name": "Malchy",
  "dollars_spent": 220
}, {
  "id": 27,
  "first_name": "Yule",
  "dollars_spent": 291
}, {
  "id": 28,
  "first_name": "Andrei",
  "dollars_spent": 273
}, {
  "id": 29,
  "first_name": "Randi",
  "dollars_spent": 162
}, {
  "id": 30,
  "first_name": "Lucy",
  "dollars_spent": 283
}, {
  "id": 31,
  "first_name": "Sigmund",
  "dollars_spent": 291
}, {
  "id": 32,
  "first_name": "Corenda",
  "dollars_spent": 230
}, {
  "id": 33,
  "first_name": "Kari",
  "dollars_spent": 43
}, {
  "id": 34,
  "first_name": "Leda",
  "dollars_spent": 498
}, {
  "id": 35,
  "first_name": "Tyson",
  "dollars_spent": 141
}];